USE [FenXs]
GO
DROP PROCEDURE Users_InsertUser
GO
DROP PROCEDURE Users_CheckEmail
GO
DROP PROCEDURE Users_CheckLogin
GO
DROP PROCEDURE Users_GetUser
GO
DROP PROCEDURE Users_GetUserById
GO
DROP PROCEDURE Users_GetAllUsers
GO
DROP PROCEDURE Users_UpdateEmail
GO
DROP PROCEDURE Users_UpdatePassword
GO
DROP PROCEDURE Users_UpdateAdmin
GO
DROP PROCEDURE Users_UpdateBanned
GO
DROP PROCEDURE Users_UpdateActive
GO
DROP PROCEDURE Users_UpdateModerator
GO
DROP PROCEDURE Users_RemoveUser
GO
DROP PROCEDURE GetAllNews
GO
DROP PROCEDURE GetCategories
GO
DROP PROCEDURE GetTenNews
GO
DROP PROCEDURE InsertNews
GO
DROP PROCEDURE RemoveNews
GO
DROP PROCEDURE UpdateNews
GO
DROP DATABASE [FenXs]